#!/usr/bin/env python3
"""
generate_paper.py

Generates a 5-9 page mini research paper PDF using ReportLab.
Data source: results/20260730_210528
"""

import os
import csv
from pathlib import Path
from datetime import datetime

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, ListFlowable, ListItem
)
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT

# =============================================================================
# CONFIGURATION
# =============================================================================
TIMESTAMP = "20260730_210528"
BASE_DIR = Path(__file__).parent.parent
RESULTS_DIR = BASE_DIR / "results"
PAPER_FIGURES_DIR = RESULTS_DIR / "paper_figures" / TIMESTAMP
REGIME_DIR = RESULTS_DIR / "regime_analysis"
FIGURES_DIR = RESULTS_DIR / "figures"
OUTPUT_PDF = RESULTS_DIR / "paper.pdf"

# Data files
SUMMARY_CSV = RESULTS_DIR / f"summary_{TIMESTAMP}.csv"
REGIME_SUMMARY_CSV = REGIME_DIR / "regime_summary.csv"
CONFIG_JSON = RESULTS_DIR / f"config_{TIMESTAMP}.json"

# Figure files (we use the PNGs generated by visualization.py)
FIG_MODEL_COMP = PAPER_FIGURES_DIR / "model_comparison.png"
FIG_RMSE_SHARPE = PAPER_FIGURES_DIR / "rmse_vs_sharpe.png"
FIG_PER_FACTOR = PAPER_FIGURES_DIR / "per_factor_rmse.png"
FIG_REGIME_PROBS = PAPER_FIGURES_DIR / "regime_probabilities.png"
FIG_DOMINANT = PAPER_FIGURES_DIR / "dominant_regime.png"
FIG_REGIME_CHAR = PAPER_FIGURES_DIR / "regime_characteristics.png"
FIG_ARCHITECTURE = FIGURES_DIR / "moe_architecture_vertical_20260730_215355.png"

# Ensure output directory exists
OUTPUT_PDF.parent.mkdir(parents=True, exist_ok=True)


# =============================================================================
# DATA LOADING HELPERS
# =============================================================================
def load_csv_to_dict(csv_path):
    """Load a CSV and return a list of dicts."""
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing: {csv_path}")
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        return list(reader)

def load_summary():
    """Load the summary CSV and return as list of dicts."""
    return load_csv_to_dict(SUMMARY_CSV)

def load_regime_summary():
    """Load regime_summary.csv."""
    return load_csv_to_dict(REGIME_SUMMARY_CSV)


# =============================================================================
# STYLE SETUP
# =============================================================================
def get_styles():
    styles = getSampleStyleSheet()
    
    # Title
    styles.add(ParagraphStyle(
        name='PaperTitle',
        parent=styles['Title'],
        fontName='Times-Roman',
        fontSize=18,
        leading=22,
        alignment=TA_CENTER,
        spaceAfter=12
    ))
    
    # Author
    styles.add(ParagraphStyle(
        name='Author',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=12,
        alignment=TA_CENTER,
        spaceAfter=6
    ))
    
    # Date
    styles.add(ParagraphStyle(
        name='DateLine',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=10,
        alignment=TA_CENTER,
        spaceAfter=24,
        textColor=colors.grey
    ))
    
    # Abstract
    styles.add(ParagraphStyle(
        name='Abstract',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=11,
        leading=14,
        spaceAfter=12,
        alignment=TA_JUSTIFY
    ))
    
    # Section Heading
    styles.add(ParagraphStyle(
        name='SectionHeading',
        parent=styles['Heading2'],
        fontName='Times-Bold',
        fontSize=13,
        spaceAfter=10,
        spaceBefore=14
    ))
    
    # Subsection Heading
    styles.add(ParagraphStyle(
        name='SubHeading',
        parent=styles['Heading3'],
        fontName='Times-Bold',
        fontSize=11,
        spaceAfter=6,
        spaceBefore=8
    ))
    
    # Body Text (renamed to PaperBody to avoid conflict)
    styles.add(ParagraphStyle(
        name='PaperBody',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=11,
        leading=14,
        spaceAfter=6,
        alignment=TA_JUSTIFY
    ))
    
    # Caption
    styles.add(ParagraphStyle(
        name='Caption',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=9,
        leading=11,
        alignment=TA_CENTER,
        spaceAfter=10
    ))
    
    # Table Header
    styles.add(ParagraphStyle(
        name='TableHeader',
        parent=styles['Normal'],
        fontName='Times-Bold',
        fontSize=10,
        alignment=TA_CENTER
    ))
    
    # Table Cell
    styles.add(ParagraphStyle(
        name='TableCell',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=9,
        alignment=TA_CENTER
    ))
    
    return styles


# =============================================================================
# BUILD PAPER CONTENT
# =============================================================================
def build_paper_content(styles):
    content = []
    
    # --- ABSTRACT ---
    content.append(Paragraph("Mixture of Experts for Regime-Aware Factor Timing", styles['PaperTitle']))
    content.append(Paragraph("Ken Ira Lacson Talingting", styles['Author']))
    content.append(Paragraph("July 30, 2026", styles['DateLine']))
    
    content.append(Paragraph("<b>Abstract</b>", styles['SectionHeading']))
    content.append(Paragraph(
        "Equity factor premiums exhibit significant time variation that is widely believed to be related to "
        "macroeconomic conditions. However, the precise nature of these relationships and the optimal way to "
        "incorporate them into dynamic allocation strategies remains an open question. This paper presents a "
        "reproducible, open-source benchmark for evaluating probabilistic regime-aware models for factor timing. "
        "We compare a Mixture of Experts (MoE) model—which explicitly represents uncertainty over latent economic "
        "regimes—against several deterministic baselines, including persistence, rolling average, linear regression, "
        "and random forest. Using an expanding-window backtest over 83 out-of-sample months from 2019 to 2026, "
        "we find that the MoE model generates a Sharpe ratio of 1.66 and an annualized return of 84.68%, while "
        "maintaining a maximum drawdown of only -7.06%. The model identifies four distinct latent regimes with "
        "economically interpretable return and volatility characteristics. All code and data are publicly available "
        "to facilitate reproducibility and extension.",
        styles['Abstract']
    ))
    content.append(Spacer(1, 0.2*inch))
    
    # --- 1. INTRODUCTION ---
    content.append(Paragraph("1. Introduction", styles['SectionHeading']))
    content.append(Paragraph(
        "Equity factor investing—allocating across styles such as Value, Momentum, Quality, and Low Volatility—is "
        "a cornerstone of modern portfolio construction. However, factor premiums are not stable over time; they "
        "exhibit pronounced cyclicality that appears connected to changing macroeconomic conditions. This time "
        "variation poses a practical challenge: how should an investor allocate across factors when the future "
        "performance of each factor is uncertain and dependent on latent, unobservable economic states?",
        styles['PaperBody']
    ))
    content.append(Paragraph(
        "This project addresses this challenge by investigating whether a probabilistic model that explicitly "
        "represents uncertainty over regimes can provide a coherent and practical framework for dynamic factor "
        "allocation. Specifically, we implement a Mixture of Experts (MoE) model with a softmax gating network and "
        "linear experts trained via Expectation-Maximization. We compare this approach against simple heuristics "
        "(persistence, rolling average) and standard machine learning baselines (linear regression, random forest) "
        "using an expanding-window backtest with realistic transaction costs.",
        styles['PaperBody']
    ))
    content.append(Paragraph(
        "The primary contribution of this work is not a claim of market-beating performance, but rather a "
        "transparent, reproducible benchmark for evaluating regime-aware methods in factor timing. The full code, "
        "data pipeline, and evaluation framework are open-source, enabling practitioners and researchers to "
        "extend, critique, and build upon this foundation.",
        styles['PaperBody']
    ))
    
    # --- 2. METHODOLOGY ---
    content.append(Paragraph("2. Methodology", styles['SectionHeading']))
    
    content.append(Paragraph("2.1 Data", styles['SubHeading']))
    content.append(Paragraph(
        "We use monthly data from August 2013 to July 2026 (156 months). The equity factors are proxied by "
        "six liquid ETFs: SPY (Market), IWD (Value), MTUM (Momentum), QUAL (Quality), USMV (Low Volatility), "
        "and VIX (Volatility Index). Macroeconomic indicators are sourced from FRED, including CPI, Industrial "
        "Production, Unemployment Rate, and Treasury term spreads. Feature sets include lagged factor returns "
        "(lags 1, 3, 6, and 12 months) and macroeconomic indicators, resulting in 96 features for the "
        "FRED-enhanced configuration.",
        styles['PaperBody']
    ))
    
    content.append(Paragraph("2.2 Models", styles['SubHeading']))
    content.append(Paragraph(
        "We evaluate models across three levels of complexity: (1) non-ML heuristics—persistence and 12-month "
        "rolling average; (2) standard ML baselines—linear regression and random forest (100 trees, max depth 10); "
        "(3) a simple exponentially weighted momentum model (12-month window, decay=0.9) which serves as a trend-following "
        "baseline; and (4) the primary contribution—a Mixture of Experts (MoE) model with K=4 linear experts, softmax gating, "
        "and EM training for 100 iterations with Ridge regularization (alpha=0.1).",
        styles['PaperBody']
    ))
    
    content.append(Paragraph("2.3 Evaluation Framework", styles['SubHeading']))
    content.append(Paragraph(
        "We employ an expanding-window backtest with a minimum training size of 132 months and a 1-month test "
        "window, yielding 83 out-of-sample predictions from August 2019 to June 2026. Allocations are magnitude-"
        "weighted long-only on positive predictions, with 10 basis points transaction costs. Metrics include "
        "predictive accuracy (RMSE, MAE) and investment performance (Sharpe ratio, annualized return, maximum "
        "drawdown, Calmar ratio, and win rate).",
        styles['PaperBody']
    ))



    content.append(Paragraph(
        "As an additional baseline, we consider a static 1/N equal-weight portfolio consisting of the equity factors. "
        "While not explicitly listed in Table 1, this passive allocation serves as a baseline to evaluate whether dynamic "
        "factor timing adds true risk-adjusted value over simple diversification.",
        styles['PaperBody']
    ))


    
    # --- 3. RESULTS ---
    content.append(PageBreak())
    content.append(Paragraph("3. Results", styles['SectionHeading']))
    
    content.append(Paragraph("3.1 Model Comparison", styles['SubHeading']))
    content.append(Paragraph(
        "Table 1 presents the out-of-sample performance of all models. The MoE model achieves the highest "
        "annualized return (84.68%) with a Sharpe ratio of 1.66 and a maximum drawdown of only -7.06%, "
        "demonstrating strong risk-adjusted performance. While the momentum model achieves a higher Sharpe "
        "ratio (2.16), it does so with lower annualized return (49.87%) and comparable risk characteristics. "
        "The MoE model's performance highlights the potential value of regime-aware allocation, even when "
        "point predictions are less accurate than simpler models.",
        styles['PaperBody']
    ))
    
    # Table 1
    summary_data = load_summary()
    table_data = [
        ["Model", "RMSE", "MAE", "Sharpe", "Ann. Return", "Max DD", "Calmar", "Win Rate"]
    ]
    for row in summary_data:
        table_data.append([
            row['model'].replace('_', ' ').title(),
            f"{float(row['rmse']):.2f}",
            f"{float(row['mae']):.2f}",
            f"{float(row['sharpe']):.2f}",
            f"{float(row['ann_return']):.1f}%",
            f"{float(row['max_drawdown']):.1f}%",
            f"{float(row['calmar']):.2f}",
            f"{float(row['win_rate']):.2f}"
        ])
    
    table = Table(table_data, colWidths=[1.1*inch, 0.7*inch, 0.7*inch, 0.7*inch, 0.9*inch, 0.8*inch, 0.7*inch, 0.7*inch])
    table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Times-Roman'),
        ('FONTNAME', (0,0), (-1,0), 'Times-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
    ]))
    content.append(table)
    content.append(Paragraph("<i>Table 1: Out-of-sample performance comparison across all models.</i>", styles['Caption']))
    content.append(Spacer(1, 0.1*inch))
    
    # Figure 1: Model comparison bar chart
    if FIG_MODEL_COMP.exists():
        content.append(Image(str(FIG_MODEL_COMP), width=7.5*inch, height=4.5*inch, kind='proportional'))
        content.append(Paragraph("<i>Figure 1: Model comparison across key performance metrics.</i>", styles['Caption']))
    content.append(Spacer(1, 0.15*inch))
    
    # Figure 2: RMSE vs Sharpe
    if FIG_RMSE_SHARPE.exists():
        content.append(Image(str(FIG_RMSE_SHARPE), width=6*inch, height=4*inch, kind='proportional'))
        content.append(Paragraph("<i>Figure 2: Trade-off between predictive accuracy (RMSE) and investment performance (Sharpe).</i>", styles['Caption']))
    content.append(Spacer(1, 0.15*inch))
    
    # Figure 3: Per-factor RMSE
    if FIG_PER_FACTOR.exists():
        content.append(Image(str(FIG_PER_FACTOR), width=7*inch, height=4.5*inch, kind='proportional'))
        content.append(Paragraph("<i>Figure 3: Per-factor RMSE heatmap. VIX is consistently the hardest factor to predict.</i>", styles['Caption']))
    content.append(Spacer(1, 0.15*inch))
    
    content.append(Paragraph("3.2 Regime Analysis", styles['SubHeading']))
    content.append(Paragraph(
        "The MoE model identifies four latent regimes with distinct return and volatility characteristics (Table 2). "
        "Regime 2 exhibits the highest average return (2.10%) and volatility (8.84%), while Regime 3 occurs most "
        "frequently (32.61%) with moderate return and volatility. Figure 4 displays the regime probabilities over "
        "time, revealing meaningful transitions that suggest sensitivity to changing market conditions.",
        styles['PaperBody']
    ))
    
    # Table 2: Regime summary
    regime_data = load_regime_summary()
    regime_table_data = [
        ["Regime", "Frequency", "Avg. Return", "Avg. Volatility"]
    ]
    for row in regime_data:
        regime_table_data.append([
            row['regime'].replace('_', ' '),
            f"{float(row['frequency'])*100:.1f}%",
            f"{float(row['avg_return']):.2f}%",
            f"{float(row['avg_volatility']):.2f}%"
        ])
    
    regime_table = Table(regime_table_data, colWidths=[1.2*inch, 1.2*inch, 1.5*inch, 1.5*inch])
    regime_table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Times-Roman'),
        ('FONTNAME', (0,0), (-1,0), 'Times-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
    ]))
    content.append(regime_table)
    content.append(Paragraph("<i>Table 2: Characteristics of the four latent regimes identified by the MoE model.</i>", styles['Caption']))
    content.append(Spacer(1, 0.1*inch))
    
    # Figure 4: Regime probabilities
    if FIG_REGIME_PROBS.exists():
        content.append(Image(str(FIG_REGIME_PROBS), width=7.5*inch, height=4*inch, kind='proportional'))
        content.append(Paragraph("<i>Figure 4: MoE regime probabilities over time. Regime transitions reflect changing market conditions.</i>", styles['Caption']))
    content.append(Spacer(1, 0.15*inch))
    
    # Figure 5: Dominant regime
    if FIG_DOMINANT.exists():
        content.append(Image(str(FIG_DOMINANT), width=7.5*inch, height=3*inch, kind='proportional'))
        content.append(Paragraph("<i>Figure 5: Dominant regime over the backtest period.</i>", styles['Caption']))
    content.append(Spacer(1, 0.15*inch))
    
    # Figure 6: Regime characteristics
    if FIG_REGIME_CHAR.exists():
        content.append(Image(str(FIG_REGIME_CHAR), width=6*inch, height=4*inch, kind='proportional'))
        content.append(Paragraph("<i>Figure 6: Return vs. volatility characteristics of the four regimes. Bubble size represents frequency.</i>", styles['Caption']))
    content.append(Spacer(1, 0.15*inch))
    
    # --- 4. DISCUSSION ---
    content.append(PageBreak())
    content.append(Paragraph("4. Discussion", styles['SectionHeading']))
    
    content.append(Paragraph("4.1 Key Findings", styles['SubHeading']))
    content.append(Paragraph(
        "The MoE model demonstrates that probabilistic regime awareness can provide a practical framework for "
        "factor timing. In our experimental setup, MoE achieved the highest annualized return (84.68%) while "
        "maintaining a Sharpe ratio of 1.66 and a maximum drawdown of only -7.06%. Notably, the model trades "
        "off predictive accuracy (RMSE 12.33) for superior allocation decisions, suggesting that the sign and "
        "magnitude of predictions are more important than point accuracy for investment performance.",
        styles['PaperBody']
    ))
    
    content.append(Paragraph("4.2 Regime Interpretability", styles['SubHeading']))
    content.append(Paragraph(
        "The four latent regimes identified by the MoE model exhibit economically meaningful differences. "
        "Regime 2, characterized by high return and high volatility, may correspond to periods of strong economic "
        "expansion or market stress. Regime 3, which appears most frequently, represents a more moderate baseline "
        "state. The transition dynamics shown in Figure 4 suggest that the model captures meaningful changes in "
        "market conditions, although further analysis is needed to map these regimes to specific macroeconomic "
        "events.",
        styles['PaperBody']
    ))
    
    content.append(Paragraph("4.3 Limitations", styles['SubHeading']))
    content.append(Paragraph(
        "This study has several limitations. The data sample is limited to 156 months of US equity data, "
        "which constrains model complexity and may not generalize to other markets or asset classes. The "
        "ETF proxies used may not perfectly isolate pure factor exposures. "
        "Additionally, three methodological caveats should be noted. "
        "First, the VIX is a spot index and is not directly tradable; a live implementation would require "
        "VIX futures or ETFs, which incur significant roll costs. Our backtest assumes direct spot VIX exposure, "
        "which may overstate achievable returns. "
        "Second, the model uses 96 features with only 132 training months, creating a high-dimensional feature "
        "space. While Ridge regularization and EM iteration stability mitigate this, some overfitting risk remains. "
        "Third, FRED macroeconomic indicators are subject to publication lags of 1–2 months; our backtest assumes "
        "immediate availability, which may overstate real-time performance. "
        "Finally, macroeconomic data revisions (vintage effects) are not modeled, which is a standard limitation "
        "in backtesting studies. The allocation strategy is long-only and does not incorporate short-selling or "
        "leverage, which may limit the applicability of the results to certain investment mandates.",
        styles['PaperBody']
    ))
    
    # --- 5. CONCLUSION ---
    content.append(Paragraph("5. Conclusion", styles['SectionHeading']))
    content.append(Paragraph(
        "This paper presents an open-source, reproducible benchmark for evaluating probabilistic regime-aware "
        "models in equity factor timing. The Mixture of Experts model, with its softmax gating and linear experts, "
        "demonstrated strong out-of-sample performance in our backtest, achieving a Sharpe ratio of 1.66 and an "
        "annualized return of 84.68%. The model identified four distinct latent regimes with economically "
        "interpretable characteristics.",
        styles['PaperBody']
    ))
    content.append(Paragraph(
        "We emphasize that this work is not a claim of market-beating performance, but rather a transparent "
        "contribution to the quantitative finance community. The full code, data pipeline, and evaluation "
        "framework are publicly available, enabling practitioners and researchers to extend, critique, and "
        "improve upon this work. Future directions include incorporating additional asset classes, exploring "
        "more sophisticated gating mechanisms, and conducting formal statistical significance tests.",
        styles['PaperBody']
    ))




    # --- 7. ACKNOWLEDGMENTS ---
    content.append(PageBreak())
    content.append(Paragraph("7. Acknowledgments", styles['SectionHeading']))
    content.append(Paragraph(
        "The authors acknowledge the Federal Reserve Bank of St. Louis for providing the "
        "macroeconomic data used in this study via the FRED (Federal Reserve Economic Data) "
        "API. Factor return data were sourced from yfinance.",
        styles['PaperBody']
    ))
    
    # --- 6. REFERENCES ---
    content.append(PageBreak())
    content.append(Paragraph("References", styles['SectionHeading']))
    
    refs = [
        "[1] Fama, E. F., & French, K. R. (1993). Common risk factors in the returns on stocks and bonds. "
        "<i>Journal of Financial Economics</i>, 33(1), 3-56.",
        "[2] Asness, C. S., Moskowitz, T. J., & Pedersen, L. H. (2013). Value and momentum everywhere. "
        "<i>Journal of Finance</i>, 68(3), 929-985.",
        "[3] Jacobs, R. A., Jordan, M. I., Nowlan, S. J., & Hinton, G. E. (1991). Adaptive mixtures of local experts. "
        "<i>Neural Computation</i>, 3(1), 79-87.",
        "[4] Ang, A., & Bekaert, G. (2002). International asset allocation with regime shifts. "
        "<i>Review of Financial Studies</i>, 15(4), 1137-1187.",
        "[5] Shih, W. (2020). <i>Machine Learning for Factor Investing</i>. CFA Institute Research Foundation."
    ]
    
    for ref in refs:
        content.append(Paragraph(ref, styles['PaperBody']))
        content.append(Spacer(1, 0.05*inch))
    
    # --- APPENDIX: ARCHITECTURE DIAGRAM ---
    content.append(PageBreak())
    content.append(Paragraph("Appendix A: MoE Architecture", styles['SectionHeading']))
    if FIG_ARCHITECTURE.exists():
        content.append(Image(str(FIG_ARCHITECTURE), width=6.5*inch, height=8.5*inch, kind='proportional'))
        content.append(Paragraph("<i>Figure A1: Architecture of the Mixture of Experts model used in this study. Input: 96 features (lagged factor returns + FRED macro indicators) | Output: 6 factor returns.</i>", styles['Caption']))
    
    return content


# =============================================================================
# MAIN GENERATION FUNCTION
# =============================================================================
def main():
    print("=" * 60)
    print("GENERATING MINI RESEARCH PAPER")
    print("=" * 60)
    
    # Verify all required files exist
    required_files = [
        SUMMARY_CSV, REGIME_SUMMARY_CSV, CONFIG_JSON,
        FIG_MODEL_COMP, FIG_RMSE_SHARPE, FIG_PER_FACTOR,
        FIG_REGIME_PROBS, FIG_DOMINANT, FIG_REGIME_CHAR,
        FIG_ARCHITECTURE
    ]
    
    missing_files = [f for f in required_files if not f.exists()]
    if missing_files:
        print("\n❌ ERROR: Missing the following files:")
        for f in missing_files:
            print(f"   {f}")
        print("\nPlease ensure you have run the pipeline and visualization script first.")
        return
    
    print("✅ All data files and figures found.")
    
    # Setup styles
    styles = get_styles()
    
    # Build content
    print("Building paper content...")
    story = build_paper_content(styles)
    
    # Create PDF
    print(f"Generating PDF at: {OUTPUT_PDF}")
    doc = SimpleDocTemplate(
        str(OUTPUT_PDF),
        pagesize=LETTER,
        leftMargin=0.8*inch,
        rightMargin=0.8*inch,
        topMargin=0.8*inch,
        bottomMargin=0.8*inch,
    )
    
    doc.build(story)
    print(f"✅ PDF successfully generated: {OUTPUT_PDF}")
    print(f"   Total pages: {doc.page}")

    # Add a small "do not overclaim" note to console
    print("\n" + "=" * 60)
    print("REMINDER: This paper is a mini research report for open-source documentation.")
    print("It is NOT a peer-reviewed publication. Do not present it as such.")
    print("=" * 60)


if __name__ == "__main__":
    main()